name: Rust Backend CI

on:
  push:
    paths:
      - 'server/**'
      - '.github/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: setup environment
        run: pacman -Syu --noconfirm --needed rust git curl sqlx-cli sqlite jq openssl
      - uses: actions/checkout@v3
      - name: Build & Test
        run: |
          cd server
          cargo build
          ./tests/server_test.sh
