name: Rust Backend CI

on:
  push:
    paths:
      - 'server/**'
      - '.github/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: setup environment
        run: "pacman -Syu --noconfirm --needed
          git curl
          sqlx-cli sqlite jq
          rust pkg-config openssl sccache
          deno"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: arch-linux-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: arch-linux-cargo-
      - uses: actions/cache@v3
        with:
          path: /github/home/.cache/sccache
          key: arch-linux-sccache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: arch-linux-sccache
      - name: Start Sccache Sever
        env:
          SCCACHE_DIR: /github/home/.cache/sccache
          SCCACHE_CACHE_SIZE: 2G
        run: sccache --start-server
      - name: Build & Test
        env:
          RUST_BACKTRACE: full
          RUSTC_WRAPPER: sccache
        run: |
          cd server
          cargo build
          ./tests/server_test.ts
      - run: sccache --show-stats && sccache --stop-server || true
